### ISSUE TITLE
Missing build

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/r-chemometrics-feedstock#1]
Try restarting any failed CI builds (all the dependencies should be available). Please record your attempts here to avoid duplicating effort and CI time.

**Comment by jdblischak** [comment]
The CircleCI build for R 3.3.2 failed during the upload to Anaconda Cloud:

```
Processing r-chemometrics
Using Anaconda API: https://api.anaconda.org
Traceback (most recent call last):
  File "/opt/conda/bin/upload_or_check_non_existence", line 126, in <module>
    main()
  File "/opt/conda/bin/upload_or_check_non_existence", line 115, in main
    upload(cli, meta, owner, channel)
  File "/opt/conda/bin/upload_or_check_non_existence", line 64, in upload
    env=os.environ)
  File "/opt/conda/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['anaconda', '--quiet', '-t', 'binstar.token', 'upload', '/feedstock_root/build_artefacts/linux-64/r-chemometrics-1.4.2-r3.3.2_0.tar.bz2', '--user=conda-forge', '--channel=main']' returned non-zero exit status 1.
+ exit 1
Exited with code 1
```

https://circleci.com/gh/conda-forge/r-chemometrics-feedstock/1

**Comment by jdblischak** [comment]
Could someone with permissions please restart the failed CircleCI build?

**Comment by bgruening** [comment]
All are green now, right?

**Comment by jdblischak** [comment]
No. The linux-64 build with R 3.3.2 still is not available:

https://anaconda.org/conda-forge/r-chemometrics/files

It doesn't look like the CircleCI build was restarted yet. It says it ran 2 days ago:

https://circleci.com/gh/conda-forge/r-chemometrics-feedstock/1

The badges in the README are deceiving (they are all green). You have to look at the commits to see the red X:

https://github.com/conda-forge/r-chemometrics-feedstock/commits/master

I'd restart the CircleCI build myself, but I don't have permission (I would love to gain that permission if there is a process for me to request it).

**Comment by cbrueffer** [comment]
I'm interested in that as well; the OSX build for survminer (https://github.com/conda-forge/r-survminer-feedstock/) was cancelled for some reason and a no-op commit to ```meta.yaml``` doesn't seem enough to restart it.

**Comment by jdblischak** [comment]
@cbrueffer The Travis build appears to have been restarted by your empty commit, it just hasn't run yet:

https://travis-ci.org/conda-forge/r-survminer-feedstock/builds/319150120

And you should be able to log into Travis using your conda-forge GitHub credentials to restart any feedstock that you are a maintainer for. I can restart both Travis and AppVeyor, but CircleCI has a different permission system.

**Comment by cbrueffer** [comment]
You're right, I was fooled by the empty "Current" page. Thanks for the hint!

**Comment by bgruening** [comment]
@jdblischak please revoke the circle-CI token from your github account and then allow access again. This will give you permissions. I think I have restarted it.

**Comment by jdblischak** [comment]
@bgruening Thanks for the restart! The missing package has been uploaded to Anaconda Cloud.

And also thanks for the tip for fixing CircleCI. I can now rebuild feedstocks for which I am listed as a maintainer.
